# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: 浮一大白
email: zhangliugang@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  这个人很懒，什么也不想写。
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: zhangliugang
github_username:  zhangliugang
disqus_shortname: jijifly

# Build settings
markdown: kramdown
mathjax: true

sass:
  sass_dir: _sass

permalink: /posts/:title/
texture:
  title: 浮一大白
  tagline: 普通的程序员, 爱生活
  date_format: "%b %-d, %Y"
  style: red
  showNav: true
  showPicker: false

  disqus_shortname: jijifly

  # generate social links in footer
  social_links:
    twitter: august_hentai
    github:  zhangliugang
    linkedIn: in/zhangliugang
    rss: rss

plugins:
  - jekyll-seo-tag
# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
